// Message
export const MSG_TEST = 'Test Purposes'
export const MSG_SUCCESS = 'Action completed successfully!'
export const MSG_FAIL = 'Action failed!'
export const MSG_WARNING = 'Warning, be careful!'
// Colors
export const COLOR_GREEN = 'positive'
export const COLOR_RED = 'negative'
export const COLOR_YELLOW = 'warning'
export const COLOR_SKY_BLUE = 'info'
export const COLOR_GREY = 'grey-8'
export const COLOR_PURPLE = 'purple'
export const COLOR_TEAL = 'teal'
// Icon
export const ICON_THUMB_UP = 'thumb_up'
export const ICON_WARNING = 'warning'
export const ICON_INFO = 'info'
// Position
export const POS_TOP_LEFT = 'top-left'
export const POS_TOP = 'top'
export const POS_TOP_RIGHT = 'top-right'
export const POS_LEFT = 'left'
export const POS_CENTER = 'center'
export const POS_RIGHT = 'right'
export const POS_BOTTOM_LEFT = 'bottom-left'
export const POS_BOTTOM = 'bottom'
export const POS_BOTTOM_RIGHT = 'bottom-right'
